### ISSUE TITLE
Wiki pages

### ISSUE THREAD

**Issue by kaiyisg** [ExchangeBuddy/ExchangeBuddy#10]

**Comment by WYHNUS** [comment]
Wiki seems to be the most value-added feature to the user. 
Hence, it has higher priority than story creation.

Current Wiki branch status:
- DB schema created
- Backend API points provided
     - add wiki 
     - add wiki section with initial version 
     - add new version 
     - voting for specific wiki section version (not tested)
     - view wiki 
     - view specific version of wiki section
- Frontend pages implemented
     - dummy wiki main page
     - view wiki page
     - edit wiki section

 More things need to be done before pushing wiki branch to staging server for internal testing:
1. Link recommended wiki sections based on User's home / exchange university and country
2. Bootstrap wiki data (linked with university and country)
3. track past wiki section version in frontend

**Comment by WYHNUS** [comment]
**_3. track past wiki section version_** is done
Implementing **_recommendation_** now.

**Comment by WYHNUS** [comment]
Frontend wiki recommendation main page is implemented (connected with dummy backend).
Will implement backend recommendation later...

@ZhangHanming Please help with **_2. Bootstrap wiki data (linked with university and country)_**
Thanks. :)

Based on the way we aim to bootstrap wiki, another frontend need to be implemented:
4. Enable user to add new Wiki Section

**Comment by WYHNUS** [comment]
**_backend recommendation_** is implemented for both logged-in and non-loggedin user

**Comment by WYHNUS** [comment]
**_4. Enable user to add new Wiki Section_** implemented

**Comment by WYHNUS** [comment]
Done. :D :dancing_men:
