### ISSUE TITLE
More powerful group

### ISSUE THREAD

**Issue by WYHNUS** [ExchangeBuddy/ExchangeBuddy#103]
1. Enable search for group
2. Enable adding new group to group list (NOT adding customised group)
3. Better group representation (now UI not nice)

**Comment by kaiyisg** [comment]
only way to change default groups will be through editing exchange / home uni info
extra groups will support addition and deletion, and also adding prompt when user switches groups (to support 2 user types, 1 is key in wrongly, the other one is multiple exchange - do a select groups to add dialog with picker)

**Comment by ZhangHanming** [comment]
Allow adding new groups done.

**Comment by kaiyisg** [comment]
search and adding new group done, ui has added some additional details (but largely unchanged)
