### ISSUE TITLE
/patch updateUser endpoint bug

### ISSUE THREAD

**Issue by kaiyisg** [ExchangeBuddy/ExchangeBuddy#107]
@ZhangHanming  when i send the request, does not update the server.

also, disable updating email as that is not desired behavior, and enable updating password
i will only need to update these fields:

if can integrate image uploading at this endpoint and tell me how, would be good too

@WYHNUS is this the same problem as what sam said, should not update by passing userId, if not anyone else can update for u? if so, what should i do to identify users instead?

{
  'userId': //to access who is the one updating
  'name':
  'password':
}

**Comment by WYHNUS** [comment]
Email is the primary key which should not be updated.
It will be desirable to enable link different email addresses together.

Identify through token stored in user reducer.

**Comment by ZhangHanming** [comment]
@kaiyisg update user endpoint fixed

**Comment by kaiyisg** [comment]
@ZhangHanming endpoint not fixed. refer to #87 number 3. still does not update the info when i tested
