### ISSUE TITLE
Bootstrap stories data from www site

### ISSUE THREAD

**Issue by kaiyisg** [ExchangeBuddy/ExchangeBuddy#11]

**Comment by WYHNUS** [comment]
How should we sort out the User Foreign Key constrain if the author for those articles are not registered?

**Comment by WYHNUS** [comment]
This migration is not going to happen unless we can identify the authors for the articles on the new website.

**Comment by kaiyisg** [comment]
so we will now add users by email / password, and let them change it when they first log in?

**Comment by WYHNUS** [comment]
Sure.

**Comment by WYHNUS** [comment]
Current hack solution is not sustainable though...
Push everything related with story back to later milestones.

**Comment by WYHNUS** [comment]
@ZhangHanming MAGICIAN! HOORAY!
