### ISSUE TITLE
Event api endpoint setup

### ISSUE THREAD

**Issue by kaiyisg** [ExchangeBuddy/ExchangeBuddy#12]
Endpoint required: GET group/:id/events

response: array of events (refer to how the previous group formatted and return data for fb / mu events, try to follow their format), sorted in reverse chrological order. try to do some pagenation logic too?

support: use the same libraries they use, put the api secret etc in the backend

supporting 3 types of events (corresponding to 3 types of api calls)
1. fb events                         
2. mu events
3. our own events

**Comment by ZhangHanming** [comment]
move fb and mu events sync to iteration 2
