### ISSUE TITLE
Improve user signup flow to capture larger audience

### ISSUE THREAD

**Issue by WYHNUS** [ExchangeBuddy/ExchangeBuddy#25]
Consider following four types of users:
1. Want to exchange, but know nothing else
2. Going to exchange, know exchange uni/year/sem info
3. Already involved in the exchange currently
4. Done exchange before.

**Comment by kaiyisg** [comment]
next iteration @WYHNUS ?

**Comment by WYHNUS** [comment]
Ok. Push back to next iteration

**Comment by WYHNUS** [comment]
Combined into three types:
1. Want to exchange, but know nothing else
- name 
- current uni
- email
// no grouping for now

2. Going to / Already in exchange
- name 
- current uni
- exchange uni
- exchange year
- exchange semester
- email
// three groups (same uni / same uni, same exchange uni / same )

3. Done exchange before.
// same as 2

**Comment by kaiyisg** [comment]
for seniors / alumni should include "share something" in the signup flow so we can automatically capture information, and display it somehow in the future / wiki etc?

**Comment by WYHNUS** [comment]
@ZhangHanming 
need to provide backend API for two types of user creation / authentication:
1. facebook login / authentication (will send facebookToken)
2. email and password login / authentication (will send email and password)

**Comment by WYHNUS** [comment]
Done.
