### ISSUE TITLE
Better verification logic

### ISSUE THREAD

**Issue by WYHNUS** [ExchangeBuddy/ExchangeBuddy#41]
Set a time out (like 30 minutes) for verification email.
Set a disabled period for verification email (like 3 minutes) (prevent user click multiple times).

Front-end display those information.

**Comment by ZhangHanming** [comment]
disabled period implemented. timeout is not necessary. if needed in the future, will implement

**Comment by WYHNUS** [comment]
Timeout is necessary for security reasons.

**Comment by ZhangHanming** [comment]
done
