### ISSUE TITLE
Event refresh support (without refreshing the whole page when the user clicks attend event)

### ISSUE THREAD

**Issue by kaiyisg** [ExchangeBuddy/ExchangeBuddy#44]
use the actions goForAnEventSuccessUpdate and ungoForAnEventSuccessUpdate

**Comment by kaiyisg** [comment]
not planning to support unless very bad for user experience

**Comment by WYHNUS** [comment]
This is quite necessary I believe, not just for Events, but also for stories page.
Implementing this will not only improve UX, but also alleviate traffic to server.

**Comment by kaiyisg** [comment]
build first optimize later do next milestone

**Comment by kaiyisg** [comment]
supported
