### ISSUE TITLE
Search feature to explore other groups

### ISSUE THREAD

**Issue by kaiyisg** [ExchangeBuddy/ExchangeBuddy#47]
Users should be able to search for other groups, similar to the facebook search feature on home page

**Comment by kaiyisg** [comment]
@plsgibchance i think this is not that impt ok with next iteration?

**Comment by plsgibchance** [comment]
@kaiyisg Yeh ok! This one Monday don't need to have but following week need liao. Perhaps let users add/delete groups?

**Comment by kaiyisg** [comment]
merge with #103
