### ISSUE TITLE
Callback Hell in createUser method in UserController file

### ISSUE THREAD

**Issue by WYHNUS** [ExchangeBuddy/ExchangeBuddy#5]
In back-end [UserController](https://github.com/ExchangeBuddy/ExchangeBuddy/blob/master/backend/controllers/UserController.js) **createUser** method have the follow _INEFFICIENT_ way of creating three default groups after defining an array defaultGroups contains name and id for the default groups:

`              
Group.findOrCreate({
    where: {
        name: defaultGroups[0].name,
        groupType: defaultGroups[0].id,
    }
}).spread(function(group) {
    group.addUser(user);
    return Group.findOrCreate({
        where: {
            name: defaultGroups[1].name,
            groupType: defaultGroups[1].id,
        }
    })
}).spread(function(group) {
    group.addUser(user);
    return Group.findOrCreate({
        where: {
            name: defaultGroups[2].name,
            groupType: defaultGroups[2].id,
        }
    })
}).spread(function(group) {
    group.addUser(user);
    // sent confirmation email and do other stuff here
});
`

An ideal solution would be something like:

`
var defaultGroupArray = defaultGroups.map(group => {
    return Group.findOrCreate({
        where: {
            name: group.name,
            groupType: group.id,
        }
    });
});
Promise.all(defaultGroupArray).spread((responses) => {
    responses.map(group => {
        group.addUser(user);
    });
    // sent confirmation email and do other stuff here
})
`

However, even though the value in **responses** after promise is resolved having the correct value as desired three Groups, but they are not the correct type of Group model instance, hence, an error will be thrown when calling **addUser** method

**Comment by ZhangHanming** [comment]
fixed
