### ISSUE TITLE
Landing page improvement

### ISSUE THREAD

**Issue by WYHNUS** [ExchangeBuddy/ExchangeBuddy#56]
1. Make Privacy and Term of Services accessible in the main page.
2. Background text and image not contrasting enough
3. A short description for the three buttons (features)

**Comment by kaiyisg** [comment]
adding in featured stories also on home page is a good idea (liek what we drew on the whiteboard)? @WYHNUS @plsgibchance

**Comment by kaiyisg** [comment]
can copy xfers.com

**Comment by kaiyisg** [comment]
Suyuen's comments on the tagline:
going on an exchange soon? Find travel buddies from your exchange university
show users that : App to find friends to go for exchange – connect with people while on the student exchange program – must go more clear from the get go
