### ISSUE TITLE
Change the UI for navigation buttons

### ISSUE THREAD

**Issue by WYHNUS** [ExchangeBuddy/ExchangeBuddy#59]
Header
 - Back button / Logo / Profile (picture and name)

1. Home:
 - Friends / Chat / Events / switching group

2. Post Story

3. Stories

4. Setting
 - Logout

**Comment by kaiyisg** [comment]
@plsgibchance this is the old layout we decided on monday, the new layout (jsut change group menu bar to the word "group" is ok? then everything else stays?

**Comment by plsgibchance** [comment]
@kaiyisg Yeap it's ok! Need more user test to find a better way but it's good enough for Monday. Btw the home page remember to display the people going yeh :). So need to change the position of Friends, Chat and Events

**Comment by WYHNUS** [comment]
I guess we can close this issue now.
