### ISSUE TITLE
Enable Editing for User Profile

### ISSUE THREAD

**Issue by WYHNUS** [ExchangeBuddy/ExchangeBuddy#63]
And this can be the landing page when user login for the first time.

**Comment by kaiyisg** [comment]
- should consider different use cases for the different users we have now for sign up flow

**Comment by ZhangHanming** [comment]
api endpoints implemented

**Comment by WYHNUS** [comment]
@ZhangHanming User update need to support updating following fields (some of which belongs to Exchange table):
- HomeUni 
- ExchangeUni
- Exchange year
- Exchange enrol month
The above four fields will in turn affect the groups they are in...
GLHF

**Comment by ZhangHanming** [comment]
@WYHNUS updating exchange uni is a different endpoint on /updateExchange. Will include homeUni

**Comment by ZhangHanming** [comment]
HomeUni update done

**Comment by kaiyisg** [comment]
merge with #86
