### ISSUE TITLE
Urgent stuff to settle

### ISSUE THREAD

**Issue by plsgibchance** [ExchangeBuddy/ExchangeBuddy#76]
1)  Disable verification because email goes to junk. Probably get it back up when we have done up a proper html email. Can hide the “required university email for now? “

2)  Feedback that redirect to “www” for stories is irritating. Is it possible to add a back button? Because once users logon to “www” they cannot go back to application. Another way to do it is to insert a hyperlink onto “stories” stating : click here to view current stories from our website

3)  Users key in university wrongly, cannot change. There needs to be a way for them to edit this.

**Comment by kaiyisg** [comment]
2 is done
3 need @ZhangHanming to provide endpoint for editing user profile like name, uni, etc

**Comment by kaiyisg** [comment]
@plsgibchance is junk mail still a problem? (1)

**Comment by plsgibchance** [comment]
@kaiyisg
