### ISSUE TITLE
Cancel story page redirect to website

### ISSUE THREAD

**Issue by plsgibchance** [ExchangeBuddy/ExchangeBuddy#79]
When I click stories, it redirects me to the website, but I am unable to click "back". - irritating 

Suggestions : Enable the user to click "back" without having the need to open a new tab.

**Comment by WYHNUS** [comment]
Will merge with [issue 11](https://github.com/ExchangeBuddy/ExchangeBuddy/issues/11)

**Comment by kaiyisg** [comment]
merge with #76
