### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by plsgibchance** [ExchangeBuddy/ExchangeBuddy#85]
1.	Chat function is not usable 
2.	Should allow them to chat with other people (private)
3.	Grouping feature not obvious. Just put the icon as “Groups”

**Comment by kaiyisg** [comment]
@WYHNUS @plsgibchance do we really want to support private chats? i can direct people straight to the facebook messengers as an alternative

**Comment by kaiyisg** [comment]
@ZhangHanming for 1 refer to #49

**Comment by plsgibchance** [comment]
@kaiyisg If got api to use then why not so that they will not be redirected to fb messenger and can cont using our app. Unless no chat stuff to copy online then use fb messenger

**Comment by kaiyisg** [comment]
@WYHNUS @ZhangHanming is it possible to support 1-1 chat? in time for tmr

**Comment by WYHNUS** [comment]
No time to do that before open beta, push private chat back to next iteration.

**Comment by WYHNUS** [comment]
1 and 3 currently fixed.
private chat please refer to [issue 81](https://github.com/ExchangeBuddy/ExchangeBuddy/issues/81)
