### ISSUE TITLE
Profile Page

### ISSUE THREAD

**Issue by plsgibchance** [ExchangeBuddy/ExchangeBuddy#87]
1.  Image is blurry
2.  Cannot change university
3.  Cannot edit details
4.  Clicking on other’s profile should integrate with Facebook App

**Comment by kaiyisg** [comment]
2. partially implemented. Need @ZhangHanming to change /updateUni endpoint to if i give exchangeUniId, year, and term as null (which means i am an aspiring exchanger), you delete those fields and reassign me to be an aspiring exchange on the backend

**Comment by kaiyisg** [comment]
4 is done (fb messenger)

3 needs backend endpoint to work, dosent work not for /patch updateUser

**Comment by kaiyisg** [comment]
edit endpoint tested and integrated
